#!/usr/bin/python3

from PyQt5.QtCore import QSettings, QProcess

settings = QSettings('superx-system-updatesrc')
auto_updates = settings.value('auto_updates', type=bool)
startup_install = settings.value('startup_install', type=bool)

if auto_updates:

    refresh_cache = QProcess()
    refresh_cache.start('pkcon refresh -y')
    refresh_cache.waitForFinished(-1)

    update_instance = QProcess()

    if startup_install:
        update_instance.startDetached('pkcon update -d')
    else:
        update_instance.startDetached('pkcon update -y')
