#!/usr/bin/python3

from PyQt5.QtCore import QSettings, QProcess

settings = QSettings(QSettings.NativeFormat,
                     QSettings.SystemScope,
                     'superx-system-updatesrc')
auto_updates = settings.value('auto_updates', type=bool)
startup_install = settings.value('startup_install', type=bool)

if auto_updates:
    refresh_cache = QProcess()
    refresh_cache.start('pkcon refresh -y')
    refresh_cache.waitForFinished(-1)

    update_instance = QProcess()

    if startup_install:
        update_instance.start('pkcon update -d')
        update_instance.waitForFinished(-1)
        
        offline_trigger = QProcess()
        offline_trigger.start('pkcon offline-trigger')
        
    else:
        update_instance.start('pkcon update -y')
        update_instance.waitForFinished(-1)
